/**
* Robot vacuum cleaner
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models


/**
 *  * @param id  * @param userId  * @param message */
data class Feedback (    val id: kotlin.Int? = null,    val userId: kotlin.Int? = null,    val message: kotlin.String? = null
) {
}
