/**
* Robot vacuum cleaner
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models


/**
 *  * @param robotId  * @param roomId  * @param cleaningMode  * @param id  * @param task  * @param dateTimeFrom */
data class TaskForRobot (    val robotId: kotlin.Int? = null,    val roomId: kotlin.Int? = null,    val cleaningMode: TaskForRobot.CleaningMode? = null,    val id: kotlin.Int? = null,    val task: kotlin.String? = null,    val dateTimeFrom: kotlin.String? = null
) {
    /**
    * 
    * Values: DRYCLEANING,WETCLEANING
    */
    enum class CleaningMode(val value: kotlin.String){
        DRYCLEANING("DRY_CLEANING"),
        WETCLEANING("WET_CLEANING");
    }
}
