/**
* Robot vacuum cleaner
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models


/**
 *  * @param userId  * @param firstName  * @param lastName  * @param password */
data class User (    val userId: kotlin.Int? = null,    val firstName: kotlin.String? = null,    val lastName: kotlin.String? = null,    val password: kotlin.String? = null
) {
}
